apiVersion: v1
kind: Service
metadata:
  name: php8_1_mn #while file
spec:
  selector:
    app: php8_1_ssm #which pod
  ports:
  - port: 80 #which port
    protocol: TCPs
    targetPort: 9200 #port to expose
