apiVersion: v1
kind: Service
metadata:
  name: ngninx_backed_1 #file anme
spec:
  selector:
    app: php8_1_ssm #pod lable
  ports:
  - port: 80 #which port
    protocol: TCP
    targetPort: 9200 #port to expose
